# Generated by Django 5.1.4 on 2026-08-09 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_seed_base_units'),
        ('procurement', '0003_numbersequence_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='quantity_base',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productunit'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity_invoiced',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity_ordered',
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='quantity_rejected',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
