# Generated by Django 5.1.4 on 2026-08-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_purchaseorderline_quantity_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='quantity_expected',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='goodsreceiptline',
            name='quantity_rejected',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
