# Generated by Django 5.1.4 on 2026-08-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_alter_goodsreceiptline_quantity_expected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='quantity_approved',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='requisitionline',
            name='quantity_ordered',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
    ]
