# Generated by Django 5.1.4 on 2026-08-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_alter_requisitionline_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_via',
            field=models.CharField(blank=True, default='', help_text='Carrier or mode — e.g. DHL, own vehicle, Volcano bus.', max_length=120),
        ),
    ]
