# Generated by Django 5.1.4 on 2026-08-04 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("iam", "0004_auditlog_organization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PharmacyProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "retail_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("min_stock_level", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacy_products",
                        to="iam.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pharmacy_listings",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product__generic_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "product"), name="uniq_pharmacy_product"
                    )
                ],
            },
        ),
    ]
