# Generated by Django 5.1.4 on 2026-08-04 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("iam", "0004_auditlog_organization_and_more"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("batch_number", models.CharField(max_length=100)),
                ("manufacture_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField()),
                ("quantity_available", models.PositiveIntegerField(default=0)),
                (
                    "wholesale_cost",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("storage_location", models.CharField(blank=True, default="", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("QUARANTINE", "Quarantine"),
                            ("EXPIRED", "Expired"),
                            ("RECALLED", "Recalled"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_batches",
                        to="iam.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date", "batch_number"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("batch_number", models.CharField(blank=True, default="", max_length=100)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("INTAKE", "Supplier intake"),
                            ("TRANSFER_IN", "Transfer in"),
                            ("TRANSFER_OUT", "Transfer out"),
                            ("SALE", "Sale"),
                            ("WASTAGE", "Wastage"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("RECALL", "Recall"),
                        ],
                        max_length=30,
                    ),
                ),
                ("quantity_delta", models.IntegerField()),
                ("reference_type", models.CharField(blank=True, default="", max_length=50)),
                ("reference_id", models.CharField(blank=True, default="", max_length=64)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.inventorybatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="iam.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.product"
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddIndex(
            model_name="inventorybatch",
            index=models.Index(
                fields=["organization", "product", "expiry_date"],
                name="inventory_i_organiz_5a4e95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="inventorybatch",
            index=models.Index(fields=["batch_number"], name="inventory_i_batch_n_9bceae_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventorybatch",
            constraint=models.UniqueConstraint(
                fields=("organization", "product", "batch_number"), name="uniq_org_product_batch"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["organization", "product", "occurred_at"],
                name="inventory_s_organiz_ab3f8f_idx",
            ),
        ),
    ]
