# Generated by Django 5.1.4 on 2026-08-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventorybatch_stockmovement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorybatch",
            name="quantity_reserved",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
