# Generated by Django 5.1.4 on 2026-08-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_inventorybatch_quantity_reserved"),
    ]

    operations = [
        migrations.AddField(
            model_name="pharmacyproduct",
            name="wholesale_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
