# Generated by Django 5.1.4 on 2026-08-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_pharmacyproduct_wholesale_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("INTAKE", "Supplier intake"),
                    ("TRANSFER_IN", "Transfer in"),
                    ("TRANSFER_OUT", "Transfer out"),
                    ("SALE", "Sale"),
                    ("RETURN", "Customer return / sale void"),
                    ("WASTAGE", "Wastage"),
                    ("ADJUSTMENT", "Adjustment"),
                    ("RECALL", "Recall"),
                ],
                max_length=30,
            ),
        ),
    ]
