# Generated by Django 5.1.4 on 2026-08-04 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_controlled_schedule_and_more"),
        ("iam", "0006_organization_contact_person_organization_currency_and_more"),
        ("inventory", "0005_alter_stockmovement_movement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorybatch",
            name="source_org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="iam.organization",
            ),
        ),
        migrations.AddField(
            model_name="inventorybatch",
            name="source_supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplied_batches",
                to="catalog.supplier",
            ),
        ),
    ]
