# Generated by Django 5.1.4 on 2026-08-06 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pricelist_product_ddd_product_is_essential_and_more'),
        ('iam', '0016_apikey'),
        ('inventory', '0006_inventorybatch_source_org_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BinLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aisle', models.CharField(blank=True, default='', max_length=20)),
                ('shelf', models.CharField(blank=True, default='', max_length=20)),
                ('bin_code', models.CharField(max_length=50)),
                ('is_occupied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['zone', 'bin_code'],
            },
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='is_consignment',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BatchRecall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recall_reference', models.CharField(max_length=100, unique=True)),
                ('manufacturer_name', models.CharField(blank=True, default='', max_length=100)),
                ('batch_number', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated / Frozen'), ('IN_PROGRESS', 'Quarantine in Progress'), ('COMPLETED', 'Completed & Disposed')], default='INITIATED', max_length=20)),
                ('recalled_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='iam.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'ordering': ['-recalled_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='bin_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='inventory.binlocation'),
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PASSED', 'Passed QC & Released'), ('FAILED', 'Failed QC & Rejected'), ('PENDING_REVIEW', 'Pending Review')], default='PENDING_REVIEW', max_length=20)),
                ('visual_integrity_ok', models.BooleanField(default=True)),
                ('temp_indicator_ok', models.BooleanField(default=True)),
                ('coa_document_url', models.CharField(blank=True, default='', max_length=255)),
                ('inspection_notes', models.TextField(blank=True, default='')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='inventory.inventorybatch')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=100, unique=True)),
                ('count_type', models.CharField(choices=[('CYCLE_COUNT', 'Cycle Count (ABC)'), ('FULL_PHYSICAL', 'Full Physical Count'), ('SPOT_CHECK', 'Spot Check')], default='CYCLE_COUNT', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved & Reconciled')], default='DRAFT', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_audits', to=settings.AUTH_USER_MODEL)),
                ('counter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counted_audits', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='iam.organization')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_qty', models.IntegerField()),
                ('counted_qty', models.IntegerField()),
                ('variance_qty', models.IntegerField()),
                ('variance_reason', models.CharField(blank=True, default='', max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorybatch')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockcount')),
            ],
            options={
                'ordering': ['batch__product__generic_name'],
            },
        ),
        migrations.CreateModel(
            name='StockDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_no', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved for Destruction'), ('DESTROYED', 'Destroyed & Certified')], default='DRAFT', max_length=20)),
                ('reason', models.CharField(choices=[('EXPIRED', 'Expired Stock'), ('DAMAGED', 'Damaged / Compromised Stock'), ('RECALLED', 'Recalled Stock')], default='EXPIRED', max_length=20)),
                ('secondary_witness_name', models.CharField(blank=True, default='', max_length=100)),
                ('destruction_method', models.CharField(blank=True, default='INCINERATION', max_length=100)),
                ('certificate_no', models.CharField(blank=True, default='', max_length=100)),
                ('destroyed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='iam.organization')),
                ('primary_witness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witnessed_disposals_primary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('AMBIENT', 'Ambient (15–25 °C)'), ('COLD_CHAIN', 'Cold Chain (2–8 °C)'), ('FREEZER', 'Freezer (-20 °C)'), ('CONTROLLED_SAFE', 'Controlled Substance Safe'), ('HAZARDOUS', 'Hazardous / Cytotoxic')], default='AMBIENT', max_length=30)),
                ('temp_min_celsius', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('temp_max_celsius', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('humidity_max_percent', models.DecimalField(decimal_places=2, default=65.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_zones', to='iam.organization')),
            ],
            options={
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.AddField(
            model_name='binlocation',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='inventory.storagezone'),
        ),
        migrations.CreateModel(
            name='TemperatureSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('calibration_due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_sensors', to='iam.organization')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='inventory.storagezone')),
            ],
            options={
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_celsius', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('excursion_status', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('CRITICAL_BREACH', 'Critical Excursion Breach')], default='NORMAL', max_length=25)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.temperaturesensor')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='storagezone',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_org_storage_zone'),
        ),
        migrations.AddConstraint(
            model_name='binlocation',
            constraint=models.UniqueConstraint(fields=('zone', 'bin_code'), name='uniq_zone_bin_code'),
        ),
    ]
