# Generated by Django 5.1.4 on 2026-08-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_temperaturesensor_accuracy_celsius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='origin_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
