# Generated by Django 5.1.4 on 2026-08-07 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_fx_and_intercompany_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('destroyed_quantity', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposal_lines', to='inventory.inventorybatch')),
                ('disposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockdisposal')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('disposal', 'batch'), name='uniq_disposal_batch_line')],
            },
        ),
    ]
