# Generated by Django 5.1.4 on 2026-08-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_disposalline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybatch',
            name='quantity_available',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='quantity_reserved',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
    ]
