# Generated by Django 5.1.4 on 2026-08-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventorybatch_quantity_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity_delta',
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
    ]
