# Generated by Django 5.1.4 on 2026-08-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_stockmovement_quantity_delta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picktask',
            name='quantity_picked',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='picktask',
            name='quantity_requested',
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
    ]
