# Generated by Django 5.1.4 on 2026-08-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_picktask_quantity_picked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyproduct',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
