# Generated by Django 5.1.4 on 2026-08-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_pharmacyproduct_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='opened_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
