# Generated by Django 5.1.4 on 2026-08-09 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_inventorybatch_opened_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('COA', 'Certificate of Analysis'), ('GMP', 'Manufacturer GMP certificate'), ('IMPORT_PERMIT', 'Import permit / authorisation'), ('BILL_OF_LADING', 'Bill of lading'), ('CUSTOMS', 'Customs declaration'), ('COLD_CHAIN_LOG', 'Cold-chain shipping log'), ('DESTRUCTION', 'Proof of destruction'), ('RECALL_NOTICE', 'Recall notice'), ('OTHER', 'Other')], max_length=20)),
                ('document_number', models.CharField(blank=True, default='', max_length=100)),
                ('document_url', models.URLField(blank=True, default='')),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, default='', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='inventory.inventorybatch')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch', 'doc_type'], name='inventory_b_batch_i_a6d9be_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('doc_type', 'OTHER'), _negated=True), fields=('batch', 'doc_type'), name='uniq_batch_document_kind')],
            },
        ),
    ]
