# Generated by Django 5.1.4 on 2026-08-05 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0011_userdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "employee_number",
                    models.CharField(blank=True, default="", max_length=30, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("national_id", models.CharField(blank=True, default="", max_length=30)),
                ("job_title", models.CharField(blank=True, default="", max_length=100)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full time"),
                            ("PART_TIME", "Part time"),
                            ("CONTRACT", "Contract"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("PROBATION", "Probation"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="PROBATION",
                        max_length=20,
                    ),
                ),
                ("hire_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("base_salary", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("bank_account", models.CharField(blank=True, default="", max_length=50)),
                ("momo_number", models.CharField(blank=True, default="", max_length=20)),
                ("rssb_number", models.CharField(blank=True, default="", max_length=30)),
                ("next_of_kin_name", models.CharField(blank=True, default="", max_length=150)),
                ("next_of_kin_relation", models.CharField(blank=True, default="", max_length=50)),
                ("next_of_kin_phone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("address", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="iam.department",
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="iam.license",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="iam.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("NATIONAL_ID", "National ID / passport"),
                            ("PROFESSIONAL_LICENSE", "Professional licence"),
                            ("ACADEMIC_CERTIFICATE", "Academic certificate"),
                            ("EMPLOYMENT_CONTRACT", "Signed employment contract"),
                            ("POLICE_CLEARANCE", "Police clearance"),
                            ("MEDICAL_FITNESS", "Medical fitness certificate"),
                            ("BANK_PROOF", "Bank / MoMo proof"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("document_url", models.URLField(blank=True, default="")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.employee",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["organization", "employment_status"], name="hr_employee_organiz_dd004b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("national_id__gt", "")),
                fields=("national_id",),
                name="uniq_employee_national_id_when_set",
            ),
        ),
    ]
