# Generated by Django 5.1.4 on 2026-08-05 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_seed_hr_permissions"),
        ("iam", "0011_userdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_number",
            field=models.CharField(blank=True, db_index=True, default="", max_length=30),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                condition=models.Q(("employee_number__gt", "")),
                fields=("employee_number",),
                name="uniq_employee_number_when_set",
            ),
        ),
    ]
