# Generated by Django 5.1.4 on 2026-08-05 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0003_alter_employee_employee_number_and_more"),
        ("iam", "0012_organization_onboarding_status_organizationdocument"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING_APPROVAL", "Pending approval"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_runs",
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("base_salary", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("allowances", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "overtime_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "bonus_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("shift_premium", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("gross", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("paye", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "pension_employee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pension_employer",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "maternity_employee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "maternity_employer",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("cbhi", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("loans_advances", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("net_pay", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("payslip_document_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_records",
                        to="hr.employee",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="hr.payrollrun",
                    ),
                ),
            ],
            options={
                "ordering": ["employee"],
            },
        ),
        migrations.CreateModel(
            name="StatutoryRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("country", models.CharField(default="RW", max_length=2)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("PAYE_BRACKET", "PAYE bracket"),
                            ("PENSION_EMPLOYEE", "RSSB pension (employee)"),
                            ("PENSION_EMPLOYER", "RSSB pension (employer)"),
                            ("MATERNITY_EMPLOYEE", "Maternity leave (employee)"),
                            ("MATERNITY_EMPLOYER", "Maternity leave (employer)"),
                            ("CBHI", "Community-based health insurance"),
                            ("OCCUPATIONAL_HAZARD", "Occupational hazard (employer)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("band_min", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "band_max",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("rate_pct", models.DecimalField(decimal_places=3, max_digits=5)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["rate_type", "band_min"],
                "indexes": [
                    models.Index(
                        fields=["rate_type", "effective_from"],
                        name="hr_statutor_rate_ty_4ce01e_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                fields=("organization", "period_start", "period_end"),
                name="uniq_payroll_period_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrecord",
            constraint=models.UniqueConstraint(
                fields=("run", "employee"), name="uniq_payroll_record_per_run"
            ),
        ),
    ]
