# Generated by Django 5.1.4 on 2026-08-08 07:12

import apps.hr.models_people
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_record_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpdrecord',
            name='cpd_year',
            field=models.PositiveIntegerField(default=apps.hr.models_people.current_cpd_year),
        ),
    ]
