# Generated by Django 5.1.4 on 2026-08-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_cpd_year_callable_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.CharField(blank=True, default='', help_text="URL of the employee's profile photo (badge).", max_length=500),
        ),
    ]
