# Generated by Django 5.1.4 on 2026-08-10 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0011_product_dose_unit_product_doses_per_base_unit_and_more'),
        ('iam', '0023_organization_require_coa_before_release'),
        ('inventory', '0017_pharmacyproduct_image_verified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('kind', models.CharField(choices=[('COMPLAINT', 'Complaint'), ('DEVIATION', 'Deviation'), ('ADVERSE_EVENT', 'Adverse event')], max_length=20)),
                ('source', models.CharField(choices=[('PATIENT', 'Patient or customer'), ('PHARMACY', 'Pharmacy or customer organisation'), ('INTERNAL', 'Staff'), ('SUPPLIER', 'Supplier'), ('INSPECTION', 'Inspection or audit'), ('EXCURSION', 'Temperature excursion'), ('RECALL', 'Recall')], default='INTERNAL', max_length=20)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical — patient safety or licence at risk'), ('MAJOR', 'Major — product quality or compliance affected'), ('MINOR', 'Minor — no product or patient impact')], default='MINOR', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Under investigation'), ('ACTIONS_PENDING', 'Actions pending'), ('VERIFYING', 'Verifying effectiveness'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected — not a quality issue')], default='OPEN', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('reporter_name', models.CharField(blank=True, default='', max_length=150)),
                ('reporter_contact', models.CharField(blank=True, default='', max_length=150)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('investigation', models.TextField(blank=True, default='')),
                ('root_cause', models.TextField(blank=True, default='')),
                ('is_reportable', models.BooleanField(default=False)),
                ('reported_to_regulator_at', models.DateTimeField(blank=True, null=True)),
                ('regulator_reference', models.CharField(blank=True, default='', max_length=100)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_cases', to='inventory.inventorybatch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_cases', to='iam.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_cases_owned', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapaAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CORRECTIVE', 'Corrective — fix this occurrence'), ('PREVENTIVE', 'Preventive — stop it happening again'), ('IMMEDIATE', 'Immediate containment')], default='CORRECTIVE', max_length=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Done — awaiting verification'), ('VERIFIED', 'Verified effective'), ('INEFFECTIVE', 'Verified ineffective')], default='OPEN', max_length=12)),
                ('description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_note', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('effectiveness_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='quality.qualitycase')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdverseEventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_initials', models.CharField(blank=True, default='', max_length=10)),
                ('patient_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('patient_sex', models.CharField(blank=True, default='', max_length=10)),
                ('reaction', models.TextField(help_text="What happened, in the reporter's words.")),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('seriousness', models.CharField(choices=[('NON_SERIOUS', 'Non-serious'), ('SERIOUS', 'Serious — hospitalisation, disability or worse'), ('FATAL', 'Fatal')], default='NON_SERIOUS', max_length=15)),
                ('outcome', models.CharField(choices=[('RECOVERED', 'Recovered'), ('RECOVERING', 'Recovering'), ('NOT_RECOVERED', 'Not recovered'), ('FATAL', 'Fatal'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15)),
                ('causality', models.CharField(choices=[('CERTAIN', 'Certain'), ('PROBABLE', 'Probable'), ('POSSIBLE', 'Possible'), ('UNLIKELY', 'Unlikely'), ('UNASSESSED', 'Not yet assessed')], default='UNASSESSED', max_length=12)),
                ('concomitant_medicines', models.TextField(blank=True, default='')),
                ('dechallenge', models.BooleanField(blank=True, help_text='Did the reaction settle when the medicine was stopped?', null=True)),
                ('rechallenge', models.BooleanField(blank=True, help_text='Did it return when the medicine was restarted?', null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_event', to='quality.qualitycase')),
            ],
        ),
        migrations.AddIndex(
            model_name='qualitycase',
            index=models.Index(fields=['organization', 'status'], name='quality_qua_organiz_03fe12_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycase',
            index=models.Index(fields=['kind', 'status'], name='quality_qua_kind_fef88e_idx'),
        ),
        migrations.AddIndex(
            model_name='qualitycase',
            index=models.Index(fields=['batch'], name='quality_qua_batch_i_646244_idx'),
        ),
        migrations.AddIndex(
            model_name='capaaction',
            index=models.Index(fields=['case', 'status'], name='quality_cap_case_id_50ed48_idx'),
        ),
    ]
