# Generated by Django 5.1.4 on 2026-08-10 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_dose_unit_product_doses_per_base_unit_and_more'),
        ('iam', '0023_organization_require_coa_before_release'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='', max_length=30, unique=True)),
                ('kind', models.CharField(choices=[('SELF_INSPECTION', 'Self-inspection'), ('BRANCH', 'Branch audit'), ('SUPPLIER', 'Supplier audit'), ('PROCESS', 'Process audit'), ('REGULATORY', 'Regulatory inspection')], default='SELF_INSPECTION', max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In progress'), ('REPORTING', 'Reporting'), ('CLOSED', 'Closed')], default='PLANNED', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('scope', models.TextField(help_text='What is being examined, and what is deliberately not.')),
                ('planned_for', models.DateField(blank=True, null=True)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_engagements', to='iam.organization')),
                ('subject_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='iam.organization')),
                ('subject_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.supplier')),
            ],
            options={
                'ordering': ['-planned_for', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical — patient safety or licence at risk'), ('MAJOR', 'Major — product quality or compliance affected'), ('MINOR', 'Minor — no product or patient impact')], default='MINOR', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESPONDED', 'Management responded'), ('ACTIONS_RAISED', 'Actions raised'), ('CLOSED', 'Closed')], default='OPEN', max_length=15)),
                ('observation', models.TextField(help_text='What was seen, with the evidence for it.')),
                ('requirement', models.CharField(blank=True, default='', help_text='The SOP, licence condition or regulation this departs from.', max_length=255)),
                ('management_response', models.TextField(blank=True, default='')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_finding', to='quality.qualitycase')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='quality.auditengagement')),
            ],
            options={
                'ordering': ['-severity', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='auditengagement',
            index=models.Index(fields=['organization', 'status'], name='quality_aud_organiz_a738cc_idx'),
        ),
    ]
