# Generated by Django 5.1.4 on 2026-08-06 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0017_user_tin_payroll_email_reports_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('source_doc_type', models.CharField(blank=True, default='', max_length=50)),
                ('source_doc_id', models.CharField(blank=True, default='', max_length=64)),
                ('source_line_id', models.CharField(blank=True, default='', max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending dispatch'), ('DISPATCHED', 'Dispatched successfully'), ('DEAD', 'Exhausted retries (dead-letter)')], db_index=True, default='PENDING', max_length=12)),
                ('retries', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, default='', max_length=80)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Tenant scope. Null for cross-tenant events (e.g. platform announcements).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='iam.organization')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status', 'id'], name='events_outb_status_edeea3_idx'), models.Index(fields=['event_type', 'source_doc_type', 'source_doc_id', 'source_line_id'], name='idx_outbox_idempotency')],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'source_doc_type', 'source_doc_id', 'source_line_id'), name='uniq_outbox_idempotency')],
            },
        ),
    ]
