# Generated by Django 5.1.4 on 2026-08-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0002_seed_approval_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='self_approved',
            field=models.BooleanField(default=False),
        ),
    ]
