# Generated by Django 5.1.4 on 2026-08-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_supplierbill_supplierbillpayment_and_more"),
        ("iam", "0012_organization_onboarding_status_organizationdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalline",
            name="is_reconciled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="journalline",
            name="reconciled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="journalline",
            name="statement_reference",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("BANK", "Bank"),
                            ("MOMO", "Mobile money (MTN MoMo)"),
                            ("AIRTEL", "Mobile money (Airtel)"),
                            ("CASH", "Cash on hand"),
                        ],
                        default="BANK",
                        max_length=10,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=150)),
                ("account_number", models.CharField(blank=True, default="", max_length=50)),
                ("currency", models.CharField(default="RWF", max_length=3)),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gl_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_account",
                        to="finance.account",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
