# Generated by Django 5.1.4 on 2026-08-06 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_accountingperiod'),
        ('iam', '0016_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('EQUIPMENT', 'Medical & Cold-Chain Equipment'), ('FURNITURE', 'Pharmacy Furniture & Fixtures'), ('VEHICLE', 'Delivery Vehicle'), ('IT_HARDWARE', 'IT & POS Hardware'), ('LEASEHOLD', 'Leasehold Improvements')], default='EQUIPMENT', max_length=30)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('useful_life_years', models.PositiveIntegerField(default=5)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='iam.organization')),
            ],
            options={
                'ordering': ['-acquisition_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('sdc_id', models.CharField(blank=True, default='', max_length=50)),
                ('mrc_number', models.CharField(blank=True, default='', max_length=50)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_class_a', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_class_b', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_class_c', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('qr_code_payload', models.TextField(blank=True, default='')),
                ('fiscalized_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_records', to='iam.organization')),
            ],
            options={
                'ordering': ['-fiscalized_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.PositiveIntegerField(default=2026)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.account')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='iam.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='iam.organization')),
            ],
            options={
                'ordering': ['financial_year', 'department'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'department', 'financial_year', 'account'), name='uniq_budget_line')],
            },
        ),
    ]
