# Generated by Django 5.1.4 on 2026-08-06 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_fixedasset_taxrecord_budget'),
        ('iam', '0017_user_tin_payroll_email_reports_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierbill',
            name='tax_class',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AddField(
            model_name='supplierbill',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('A', 'Class A — Exempt'), ('B', 'Class B — Standard 18%'), ('C', 'Class C — Zero-rated'), ('D', 'Class D — Special')], max_length=4)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('rate_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('withholding_pct', models.DecimalField(decimal_places=2, default=0, help_text='Withholding tax rate applied to this class (0 if not subject to WHT).', max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_reference', models.CharField(blank=True, default='', help_text='RRA circular / Finance Law / Gazette reference that justifies the rate.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_codes', to='iam.organization')),
            ],
            options={
                'ordering': ['code', '-effective_from'],
                'indexes': [models.Index(fields=['organization', 'code', 'effective_from'], name='finance_tax_organiz_928bd3_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code', 'effective_from'), name='uniq_tax_code_per_effective_from')],
            },
        ),
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(blank=True, default='', max_length=30)),
                ('paid_on', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Bank transfer'), ('MOBILE_MONEY', 'Mobile money'), ('CHEQUE', 'Cheque')], default='BANK_TRANSFER', max_length=20)),
                ('rra_reference', models.CharField(blank=True, default='', help_text='RRA e-Tax receipt / bank confirmation reference.', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_payments', to='iam.organization')),
            ],
            options={
                'ordering': ['-paid_on'],
                'indexes': [models.Index(fields=['organization', 'paid_on'], name='finance_tax_organiz_9a18f1_idx')],
            },
        ),
    ]
