# Generated by Django 5.1.4 on 2026-08-06 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_openingbalance'),
        ('iam', '0017_user_tin_payroll_email_reports_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source', models.CharField(choices=[('OVERPAYMENT', 'Overpayment'), ('CREDIT_NOTE', 'Credit note'), ('RETURN', 'Return')], default='OVERPAYMENT', max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_class', models.CharField(default='B', max_length=1)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL', 'Partially paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=12)),
                ('reference_type', models.CharField(blank=True, default='', max_length=40)),
                ('reference_id', models.CharField(blank=True, default='', max_length=40)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-invoice_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('MOBILE_MONEY', 'Mobile money'), ('CHEQUE', 'Cheque')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('received_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-received_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DunningNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('REMINDER', 'Reminder (7 days)'), ('SECOND', 'Second notice (14 days)'), ('FINAL', 'Final demand (30 days)'), ('LEGAL', 'Legal / hold (60 days)')], max_length=10)),
                ('days_past_due', models.IntegerField()),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sent_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_on', '-id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='uniq_journal_reference_per_org',
        ),
        migrations.RenameIndex(
            model_name='openingbalance',
            new_name='finance_ope_organiz_14fa4c_idx',
            old_name='idx_ob_org_kind',
        ),
        migrations.RenameIndex(
            model_name='openingbalance',
            new_name='finance_ope_organiz_0be863_idx',
            old_name='idx_ob_org_kind_applied',
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='fx_provider',
            field=models.CharField(blank=True, default='', help_text="Identifier for the FX rate provider (e.g. 'BNR', 'manual').", max_length=30),
        ),
        migrations.AlterField(
            model_name='tenantsettings',
            name='statutory_remittance_day',
            field=models.PositiveSmallIntegerField(default=15, help_text='Day-of-month statutory remittances are paid (Rwanda default: 15).'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_type__gt', '')), fields=('organization', 'reference_type', 'reference_id'), name='uniq_journal_reference_per_org'),
        ),
        migrations.AddField(
            model_name='customercredit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_credits', to='iam.organization'),
        ),
        migrations.AddField(
            model_name='customercredit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_credits_issued', to='iam.organization'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_received', to='iam.organization'),
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_invoices', to='iam.organization'),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerreceipt',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='finance.customerinvoice'),
        ),
        migrations.AddField(
            model_name='customercredit',
            name='source_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits', to='finance.customerreceipt'),
        ),
        migrations.AddField(
            model_name='dunningnotice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_notices', to='finance.customerinvoice'),
        ),
        migrations.AddIndex(
            model_name='customerinvoice',
            index=models.Index(fields=['organization', 'status'], name='finance_cus_organiz_d2b025_idx'),
        ),
        migrations.AddIndex(
            model_name='customerinvoice',
            index=models.Index(fields=['customer', 'status'], name='finance_cus_custome_9db545_idx'),
        ),
        migrations.AddConstraint(
            model_name='dunningnotice',
            constraint=models.UniqueConstraint(fields=('invoice', 'level'), name='uniq_dunning_level_per_invoice'),
        ),
    ]
