# Generated by Django 5.1.4 on 2026-08-06 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_customercredit_customerinvoice_customerreceipt_and_more'),
        ('iam', '0017_user_tin_payroll_email_reports_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.CharField(max_length=30, unique=True)),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Bank transfer'), ('MOBILE_MONEY', 'Mobile money'), ('CHEQUE', 'Cheque')], default='BANK_TRANSFER', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_APPROVAL', 'Awaiting approval'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('LOCKED', 'Locked'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('scheduled_for', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approvals_required', models.PositiveSmallIntegerField(default=1)),
                ('approvals_received', models.PositiveSmallIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_filename', models.CharField(blank=True, default='', max_length=120)),
                ('disbursement_file', models.TextField(blank=True, default='')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_runs', to='iam.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRunLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payee_name', models.CharField(blank=True, default='', max_length=255)),
                ('payee_account', models.CharField(blank=True, default='', max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_lines', to='finance.supplierbill')),
                ('payment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.paymentrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentrun',
            index=models.Index(fields=['organization', 'status'], name='finance_pay_organiz_9424ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentrunline',
            constraint=models.UniqueConstraint(fields=('payment_run', 'bill'), name='uniq_bill_per_payment_run'),
        ),
    ]
