# Generated by Django 5.1.4 on 2026-08-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_fixedasset_disposal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='classification',
            field=models.CharField(blank=True, choices=[('CURRENT_ASSET', 'Current asset'), ('NON_CURRENT_ASSET', 'Non-current asset'), ('CURRENT_LIABILITY', 'Current liability'), ('NON_CURRENT_LIABILITY', 'Non-current liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('OTHER_INCOME', 'Other income'), ('COGS', 'Cost of sales'), ('OPERATING_EXPENSE', 'Operating expense'), ('DEPRECIATION', 'Depreciation & amortisation'), ('FINANCE_COST', 'Finance cost (interest)'), ('TAX_EXPENSE', 'Tax expense')], default='', help_text='Which statement line this account rolls into. Blank falls back to a sensible default for the account type.', max_length=25),
        ),
    ]
