# Generated by Django 5.1.4 on 2026-08-07 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_bank_reconciliation'),
        ('iam', '0017_user_tin_payroll_email_reports_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('PREPAYMENT', 'Prepayment (paid in advance)'), ('ACCRUAL', 'Accrual (incurred, not yet billed)')], max_length=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('periods', models.PositiveSmallIntegerField(help_text='How many months to spread across')),
                ('start_month', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('auto_reverse', models.BooleanField(default=True)),
                ('source_reference', models.CharField(blank=True, default='', max_length=120)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.costcentre')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='iam.organization')),
            ],
            options={
                'ordering': ['-start_month', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.journalentry')),
                ('reversal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.journalentry')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='finance.recurringschedule')),
            ],
            options={
                'ordering': ['period_month'],
            },
        ),
        migrations.AddIndex(
            model_name='recurringschedule',
            index=models.Index(fields=['organization', 'status'], name='finance_rec_organiz_060dab_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedulerun',
            constraint=models.UniqueConstraint(fields=('schedule', 'period_month'), name='uniq_schedule_run_per_month'),
        ),
    ]
