# Generated by Django 5.1.4 on 2026-08-07 08:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_accruals_prepayments'),
        ('iam', '0017_user_tin_payroll_email_reports_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_monetary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalline',
            name='amount_fc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='journalline',
            name='currency',
            field=models.CharField(default='RWF', max_length=3),
        ),
        migrations.AddField(
            model_name='journalline',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=12),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('rate_date', models.DateField()),
                ('rate_to_base', models.DecimalField(decimal_places=6, max_digits=14)),
                ('source', models.CharField(choices=[('BNR', 'National Bank of Rwanda'), ('BANK', 'Commercial bank'), ('MANUAL', 'Entered by hand')], default='BNR', max_length=8)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rate_date', 'currency'],
                'indexes': [models.Index(fields=['currency', 'rate_date'], name='finance_exc_currenc_606513_idx')],
                'constraints': [models.UniqueConstraint(fields=('currency', 'rate_date'), name='uniq_exchange_rate_per_day')],
            },
        ),
        migrations.CreateModel(
            name='FxRevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('net_gain', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('detail', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fx_revaluations', to='iam.organization')),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-as_of'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'as_of'), name='uniq_fx_revaluation_per_date')],
            },
        ),
    ]
