# Generated by Django 5.1.4 on 2026-08-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_fx_and_intercompany_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='ebm_mrc_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='ebm_sdc_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
