# Generated by Django 5.1.4 on 2026-08-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("generic_name", models.CharField(max_length=255)),
                ("brand_name", models.CharField(blank=True, default="", max_length=255)),
                (
                    "dosage_form",
                    models.CharField(
                        choices=[
                            ("TABLET", "Tablet"),
                            ("CAPSULE", "Capsule"),
                            ("SYRUP", "Syrup"),
                            ("INJECTION", "Injection"),
                            ("OINTMENT", "Ointment"),
                            ("DROPS", "Drops"),
                            ("INHALER", "Inhaler"),
                            ("OTHER", "Other"),
                        ],
                        default="TABLET",
                        max_length=30,
                    ),
                ),
                ("strength", models.CharField(blank=True, default="", max_length=50)),
                ("pack_size", models.CharField(blank=True, default="", max_length=50)),
                ("unit_of_measure", models.CharField(blank=True, default="", max_length=20)),
                ("atc_code", models.CharField(blank=True, default="", max_length=10)),
                ("gtin", models.CharField(blank=True, default="", max_length=14)),
                (
                    "tax_class",
                    models.CharField(
                        choices=[
                            ("A", "A — Exempt (0%)"),
                            ("B", "B — Standard (18% VAT)"),
                            ("C", "C — Zero-rated"),
                            ("D", "D — Special"),
                        ],
                        default="B",
                        max_length=1,
                    ),
                ),
                ("requires_prescription", models.BooleanField(default=False)),
                ("is_controlled_substance", models.BooleanField(default=False)),
                (
                    "storage_condition",
                    models.CharField(
                        choices=[
                            ("AMBIENT", "Ambient"),
                            ("COLD_CHAIN", "Cold chain"),
                            ("FROZEN", "Frozen"),
                        ],
                        default="AMBIENT",
                        max_length=20,
                    ),
                ),
                ("reorder_level", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.manufacturer",
                    ),
                ),
            ],
            options={
                "ordering": ["generic_name", "brand_name"],
                "indexes": [
                    models.Index(fields=["generic_name"], name="catalog_pro_generic_996956_idx"),
                    models.Index(fields=["gtin"], name="catalog_pro_gtin_10f25d_idx"),
                ],
            },
        ),
    ]
