# Generated by Django 5.1.4 on 2026-08-04 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("atc_code", models.CharField(blank=True, default="", max_length=10)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("tin", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("lead_time_days", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("barcode", models.CharField(max_length=64)),
                (
                    "packaging_level",
                    models.CharField(
                        choices=[("EACH", "Each"), ("BOX", "Box"), ("CASE", "Case")],
                        default="EACH",
                        max_length=20,
                    ),
                ),
                ("units_per_level", models.PositiveIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["packaging_level"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "barcode"), name="uniq_product_barcode"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.CharField(blank=True, default="", max_length=50)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="in_products",
                        to="catalog.activeingredient",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["ingredient__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "ingredient"), name="uniq_product_ingredient"
                    )
                ],
            },
        ),
    ]
