# Generated by Django 5.1.4 on 2026-08-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_activeingredient_supplier_productbarcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="leaflet_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="max_temp_c",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="min_temp_c",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="rra_item_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
