# Generated by Django 5.1.4 on 2026-08-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_image_url_product_leaflet_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="controlled_schedule",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="fda_registration_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="reorder_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="route_of_administration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ORAL", "Oral"),
                    ("IV", "Intravenous (IV)"),
                    ("IM", "Intramuscular (IM)"),
                    ("SUBCUTANEOUS", "Subcutaneous"),
                    ("TOPICAL", "Topical"),
                    ("INHALATION", "Inhalation"),
                    ("OPHTHALMIC", "Ophthalmic (eye)"),
                    ("NASAL", "Nasal"),
                    ("RECTAL", "Rectal"),
                    ("OTHER", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="units_per_pack",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
