# Generated by Django 5.1.4 on 2026-08-06 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_controlled_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('list_type', models.CharField(choices=[('WHOLESALE', 'Wholesale'), ('RETAIL', 'Retail'), ('PROMOTIONAL', 'Promotional'), ('CONTRACT', 'Contract')], default='RETAIL', max_length=20)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ddd',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='is_essential',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='lifecycle_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued'), ('OBSOLETE', 'Obsolete'), ('PENDING_APPROVAL', 'Pending Approval')], default='ACTIVE', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='rxnorm_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='FormularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100)),
                ('is_covered', models.BooleanField(default=True)),
                ('max_reimbursable_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('copay_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('requires_prior_auth', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulary_items', to='catalog.product')),
            ],
            options={
                'ordering': ['scheme_name', 'product__generic_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductContraindication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=255)),
                ('icd10_code', models.CharField(blank=True, default='', max_length=20)),
                ('snomed_code', models.CharField(blank=True, default='', max_length=30)),
                ('severity', models.CharField(choices=[('PRECAUTION', 'Precaution'), ('WARNING', 'Warning'), ('CONTRAINDICATED', 'Contraindicated')], default='WARNING', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contraindications', to='catalog.product')),
            ],
            options={
                'ordering': ['condition'],
            },
        ),
        migrations.CreateModel(
            name='ProductUomConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=50)),
                ('conversion_factor', models.PositiveIntegerField(default=1)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_default_dispensing', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uom_conversions', to='catalog.product')),
            ],
            options={
                'ordering': ['product__generic_name', 'unit_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('MAJOR', 'Major')], default='MODERATE', max_length=20)),
                ('effect', models.TextField(blank=True, default='')),
                ('management', models.TextField(blank=True, default='')),
                ('ingredient_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_a', to='catalog.activeingredient')),
                ('ingredient_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_b', to='catalog.activeingredient')),
            ],
            options={
                'ordering': ['ingredient_a__name', 'ingredient_b__name'],
                'constraints': [models.UniqueConstraint(fields=('ingredient_a', 'ingredient_b'), name='uniq_ingredient_interaction')],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_quantity', models.PositiveIntegerField(default=1)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.product')),
            ],
            options={
                'ordering': ['product__generic_name', 'min_quantity'],
                'constraints': [models.UniqueConstraint(fields=('price_list', 'product', 'min_quantity'), name='uniq_price_list_product_tier')],
            },
        ),
        migrations.CreateModel(
            name='ProductSubstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substitute_type', models.CharField(choices=[('GENERIC_EQUIVALENT', 'Generic equivalent'), ('THERAPEUTIC_ALTERNATIVE', 'Therapeutic alternative')], default='GENERIC_EQUIVALENT', max_length=30)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutes', to='catalog.product')),
                ('substitute_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_for', to='catalog.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'substitute_product'), name='uniq_product_substitute')],
            },
        ),
    ]
