# Generated by Django 5.1.4 on 2026-08-07 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pricelist_product_ddd_product_is_essential_and_more'),
        ('iam', '0019_seed_approval_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Whose list this is. Empty means group-wide (set by HQ).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='iam.organization'),
        ),
    ]
