# Generated by Django 5.1.4 on 2026-08-09 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_record_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SACHET', 'Sachet'), ('SUPPOSITORY', 'Suppository'), ('BOTTLE', 'Bottle'), ('TUBE', 'Tube'), ('VIAL', 'Vial'), ('AMPOULE', 'Ampoule'), ('DEVICE', 'Device'), ('BAG', 'Bag'), ('STRIP', 'Strip'), ('PACK', 'Pack'), ('CASE', 'Case'), ('CARTON', 'Carton'), ('ML', 'Millilitre'), ('G', 'Gram'), ('UNIT', 'Unit')], max_length=20)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('factor_to_base', models.DecimalField(decimal_places=3, default=1, max_digits=14)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('is_base', models.BooleanField(default=False)),
                ('is_purchase_default', models.BooleanField(default=False)),
                ('is_sale_default', models.BooleanField(default=False)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'ordering': ['product__generic_name', 'level'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='divisibility',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='split_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('divisibility__in', (1, 2, 3, 4))), name='product_divisibility_is_a_real_split'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='catalog.product'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='uniq_product_unit_code'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_base', True)), fields=('product',), name='uniq_product_base_unit'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_purchase_default', True)), fields=('product',), name='uniq_product_purchase_unit'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_sale_default', True)), fields=('product',), name='uniq_product_sale_unit'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.CheckConstraint(condition=models.Q(('factor_to_base__gt', 0)), name='product_unit_factor_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_base', True), _negated=True), ('factor_to_base', 1), _connector='OR'), name='product_base_unit_factor_is_one'),
        ),
    ]
