# Generated by Django 5.1.4 on 2026-08-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dose_unit',
            field=models.CharField(blank=True, choices=[('ML', 'Millilitre (mL)'), ('MG', 'Milligram (mg)'), ('DROP', 'Drop'), ('PUFF', 'Puff'), ('SACHET', 'Sachet'), ('UNIT', 'International unit (IU)')], default='', help_text='The unit a prescription is written in, when it differs from the stock unit.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='doses_per_base_unit',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='How many dose units one base stock unit holds — e.g. 100 mL in one bottle.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hazard_class',
            field=models.CharField(choices=[('NONE', 'No special handling'), ('CYTOTOXIC', 'Cytotoxic — segregate, gloves, spill kit'), ('FLAMMABLE', 'Flammable — away from heat, limit quantity'), ('CORROSIVE', 'Corrosive — eye protection, contained'), ('BIOHAZARD', 'Biohazard — sharps and contaminated waste route')], default='NONE', help_text='Handling hazard — drives segregation, PPE and who may pick it.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='humidity_sensitive',
            field=models.BooleanField(default=False, help_text='Absorbs moisture. Keep the desiccant; do not break the blister early.'),
        ),
        migrations.AddField(
            model_name='product',
            name='light_sensitive',
            field=models.BooleanField(default=False, help_text='Degrades in daylight. Keep in its carton; do not display on an open shelf.'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='gross_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight of one of this unit, packaging included, in grams.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productunit',
            name='volume_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Space one of this unit occupies, in millilitres (1 L = 1,000).', max_digits=12, null=True),
        ),
    ]
