# Generated by Django 5.1.4 on 2026-08-04 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distribution", "0002_reservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("driver_name", models.CharField(blank=True, default="", max_length=150)),
                ("vehicle_registration", models.CharField(blank=True, default="", max_length=50)),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dispatched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="distribution.stockorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-dispatched_at"],
            },
        ),
    ]
