# Generated by Django 5.1.4 on 2026-08-04 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distribution", "0004_goodsreceivednote_grnline_shipmentitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockorder",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="stockorder",
            name="payment_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockorder",
            name="payment_status",
            field=models.CharField(
                choices=[("UNPAID", "Unpaid"), ("PARTIAL", "Partially paid"), ("PAID", "Paid")],
                default="UNPAID",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("MOBILE_MONEY", "Mobile money"),
                            ("CHEQUE", "Cheque"),
                            ("CREDIT", "On credit"),
                        ],
                        default="BANK_TRANSFER",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, default="", max_length=100)),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_payments",
                        to="distribution.stockorder",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
