# Generated by Django 5.1.4 on 2026-08-04 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_controlled_schedule_and_more"),
        ("distribution", "0005_stockorder_amount_paid_stockorder_payment_due_date_and_more"),
        ("iam", "0006_organization_contact_person_organization_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InTransitStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("batch_number", models.CharField(max_length=100)),
                ("expiry_date", models.DateField()),
                ("quantity", models.PositiveIntegerField()),
                ("driver_name", models.CharField(blank=True, default="", max_length=150)),
                ("vehicle_plate", models.CharField(blank=True, default="", max_length=50)),
                ("dispatched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "destination_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inbound_in_transit",
                        to="iam.organization",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_transit",
                        to="distribution.stockorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.product"
                    ),
                ),
                (
                    "source_org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbound_in_transit",
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["destination_org"], name="distributio_destina_a60009_idx"),
                    models.Index(fields=["source_org"], name="distributio_source__48df07_idx"),
                ],
            },
        ),
    ]
