# Generated by Django 5.1.4 on 2026-08-06 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pricelist_product_ddd_product_is_essential_and_more'),
        ('distribution', '0006_intransitstock'),
        ('hr', '0007_employee_extended_fields'),
        ('iam', '0017_user_tin_payroll_email_reports_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested by retailer'), ('INSPECTING', 'Inspecting at depot'), ('APPROVED', 'Approved & Restocked / Credited'), ('REJECTED', 'Rejected (Damaged / Invalid)')], default='REQUESTED', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('credit_note_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_returns', to='iam.organization')),
                ('retail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_returns', to='iam.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory_code', models.CharField(default='KIGALI-CENTRAL', max_length=50)),
                ('monthly_sales_target', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commission_rate_pct', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_reps', to='hr.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_reps', to='iam.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='JourneyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rep_visits', to='iam.organization')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_plans', to='distribution.salesrepresentative')),
            ],
            options={
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('PRE_SALE', 'Pre-sale order visit'), ('VAN_SALE', 'Van sale (sell-from-stock)'), ('CALL_ONLY', 'Detailing / Call only')], default='PRE_SALE', max_length=20)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('customer_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_visits', to='iam.organization')),
                ('journey_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_logs', to='distribution.journeyplan')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_origin', to='distribution.stockorder')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_logs', to='distribution.salesrepresentative')),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_number', models.CharField(max_length=50, unique=True)),
                ('contract_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_committed_qty', models.PositiveIntegerField()),
                ('drawn_qty', models.PositiveIntegerField(default=0)),
                ('valid_until', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_tenders', to='iam.organization')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_contracts', to='iam.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'ordering': ['-valid_until'],
            },
        ),
        migrations.CreateModel(
            name='DepotProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_qty', models.PositiveIntegerField(default=0)),
                ('buffer_qty', models.PositiveIntegerField(default=0)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_published', models.BooleanField(default=True)),
                ('customer_segment', models.CharField(blank=True, default='ALL', max_length=50)),
                ('min_order_qty', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depot_listings', to='iam.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depot_listings', to='catalog.product')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('depot', 'product'), name='uniq_depot_product_listing')],
            },
        ),
        migrations.CreateModel(
            name='VanStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='van_stocks', to='distribution.salesrepresentative')),
            ],
            options={
                'ordering': ['rep', 'product'],
                'constraints': [models.UniqueConstraint(fields=('rep', 'product', 'batch_number'), name='uniq_van_stock_item')],
            },
        ),
    ]
