# Generated by Django 5.1.4 on 2026-08-07 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pricelist_product_ddd_product_is_essential_and_more'),
        ('distribution', '0007_customerreturn_salesrepresentative_journeyplan_and_more'),
        ('iam', '0017_user_tin_payroll_email_reports_to'),
        ('inventory', '0009_fx_and_intercompany_cost'),
        ('procurement', '0003_numbersequence_domain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_returned', models.PositiveIntegerField()),
                ('quantity_accepted', models.PositiveIntegerField(default=0)),
                ('quantity_rejected', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('inspection_note', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('restocked_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventorybatch')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='distribution.customerreturn')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BackorderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_fulfilled', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open — awaiting sourcing'), ('SOURCING', 'Being sourced'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=12)),
                ('origin', models.CharField(choices=[('UNLISTED', 'Not offered by the depot'), ('WITHDRAWN', 'Withdrawn from sale'), ('SHORT', 'Offered but insufficient stock'), ('SEGMENT', "Outside the offer's segment"), ('REQUEST', 'Direct buyer request')], default='SHORT', max_length=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_demand', to='iam.organization')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backorders', to='distribution.stockorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_backorders', to='procurement.purchaserequisition')),
                ('retail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_demand', to='iam.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['depot', 'status'], name='distributio_depot_i_a674f8_idx'), models.Index(fields=['depot', 'product', 'status'], name='distributio_depot_i_18efcd_idx'), models.Index(fields=['retail', 'status'], name='distributio_retail__92b723_idx')],
            },
        ),
        migrations.CreateModel(
            name='VanStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('LOAD', 'Loaded from depot'), ('SALE', 'Sold from van'), ('RETURN', 'Returned to depot'), ('ADJUST', 'Adjustment')], max_length=10)),
                ('quantity', models.IntegerField(help_text='Signed: positive adds to the van, negative removes.')),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='van_movements', to='distribution.salesrepresentative')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='van_moves', to='distribution.salesvisitlog')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rep', 'created_at'], name='distributio_rep_id_65482b_idx')],
            },
        ),
    ]
