# Generated by Django 5.1.4 on 2026-08-09 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_customerreturnline_backorderline_vanstockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
    ]
