# Generated by Django 5.1.4 on 2026-08-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0009_alter_reservation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intransitstock',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
    ]
