# Generated by Django 5.1.4 on 2026-08-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0010_alter_intransitstock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnline',
            name='quantity_damaged',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='grnline',
            name='quantity_expected',
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
        migrations.AlterField(
            model_name='grnline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
    ]
