# Generated by Django 5.1.4 on 2026-08-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0011_alter_grnline_quantity_damaged_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_approved',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_shipped',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
    ]
