# Generated by Django 5.1.4 on 2026-08-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0012_alter_orderitem_quantity_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tendercontract',
            name='drawn_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='tendercontract',
            name='total_committed_qty',
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
    ]
