# Generated by Django 5.1.4 on 2026-08-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0013_alter_tendercontract_drawn_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='depotproductlisting',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='depotproductlisting',
            name='order_multiple',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
