# Generated by Django 5.1.4 on 2026-08-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0014_depotproductlisting_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backorderline',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
        migrations.AlterField(
            model_name='backorderline',
            name='quantity_fulfilled',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
    ]
