# Generated by Django 5.1.4 on 2026-08-09 16:08

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def carry_existing_quantities_into_base(apps, schema_editor):
    """Every line written before this field existed was in base units.

    `line_total` now multiplies the published price by `quantity_base`, so
    leaving the new column at its 0 default would take the value of every
    historical B2B order line to zero — orders, statements and the money
    already invoiced against them.
    """
    OrderItem = apps.get_model("distribution", "OrderItem")
    OrderItem.objects.update(quantity_base=F("quantity_ordered"))


def unset_base_quantities(apps, schema_editor):
    OrderItem = apps.get_model("distribution", "OrderItem")
    OrderItem.objects.update(quantity_base=0)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_dose_unit_product_doses_per_base_unit_and_more'),
        ('distribution', '0016_depotproductlisting_image_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity_base',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productunit'),
        ),
        migrations.RunPython(
            carry_existing_quantities_into_base,
            unset_base_quantities,
        ),
    ]
