# Generated by Django 5.1.4 on 2026-08-04 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0004_auditlog_organization_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("PREMISES", "Premises"),
                            ("PHARMACIST", "Pharmacist"),
                            ("WHOLESALE", "Wholesale"),
                            ("RETAIL", "Retail"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("license_number", models.CharField(max_length=100)),
                ("issuing_authority", models.CharField(blank=True, default="", max_length=150)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("document_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="iam.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date"],
                "indexes": [
                    models.Index(
                        fields=["organization", "expiry_date"],
                        name="iam_license_organiz_80bbeb_idx",
                    )
                ],
            },
        ),
    ]
