# Generated by Django 5.1.4 on 2026-08-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0005_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="contact_person",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="organization",
            name="currency",
            field=models.CharField(default="RWF", max_length=3),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organization",
            name="province",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="registration_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="village",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
