# Generated by Django 5.1.4 on 2026-08-05 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('iam', '0006_organization_contact_person_organization_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='pf_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Payroll-file / staff number; usable to sign in.', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('pf_number__gt', '')), fields=('pf_number',), name='uniq_pf_number_when_set'),
        ),
        migrations.AddField(
            model_name='impersonationsession',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='impersonationsession',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonated_as', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='impersonationsession',
            index=models.Index(fields=['admin', '-started_at'], name='iam_imperso_admin_i_88faac_idx'),
        ),
    ]
