# Generated by Django 5.1.4 on 2026-08-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0008_company_organization_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=40)),
                ('action', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['resource', 'action'],
                'constraints': [models.UniqueConstraint(fields=('resource', 'action'), name='uniq_resource_action')],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='iam.permission'),
        ),
    ]
