# Generated by Django 5.1.4 on 2026-08-05 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0011_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='onboarding_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending review'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('RWANDA_FDA_LICENCE', 'Rwanda FDA premises licence'), ('NPC_LICENCE', 'NPC pharmacist licence'), ('RDB_CERTIFICATE', 'RDB registration certificate'), ('RRA_VAT', 'RRA / VAT certificate'), ('TAX_CLEARANCE', 'Tax clearance'), ('OTHER', 'Other')], max_length=30)),
                ('document_number', models.CharField(blank=True, default='', max_length=100)),
                ('document_url', models.URLField(blank=True, default='')),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_documents', to='iam.organization')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'doc_type'], name='iam_organiz_organiz_ee4a84_idx')],
            },
        ),
    ]
