# Generated by Django 5.1.4 on 2026-08-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0012_organization_onboarding_status_organizationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='brand_color',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_flags',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='STANDARD', max_length=20),
        ),
    ]
