# Generated by Django 5.1.4 on 2026-08-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0013_organization_brand_color_organization_feature_flags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
