# Generated by Django 5.1.4 on 2026-08-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0017_user_tin_payroll_email_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='approval_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default approval ceiling in RWF for this role. Empty means unlimited — reserve that for SYS_ADMIN.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Personal approval ceiling in RWF, overriding this user's roles. Leave empty to use the highest limit among their roles.", max_digits=14, null=True),
        ),
    ]
