# Generated by Django 5.1.4 on 2026-08-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0021_record_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
