# Generated by Django 5.1.4 on 2026-08-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0022_alter_company_logo_url_alter_organization_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='require_coa_before_release',
            field=models.BooleanField(default=False, help_text='Refuse to release a lot from quarantine unless its Certificate of Analysis is on file and verified.'),
        ),
    ]
