# Generated by Django 5.1.4 on 2026-08-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0025_owner_and_assistant_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_vat_registered',
            field=models.BooleanField(default=False, help_text='Registered for VAT with the RRA. Compulsory above RWF 20M turnover in 12 months, or RWF 5M in the preceding quarter. When off, no VAT is charged at the till and no VAT appears on an invoice.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='vat_registration_no',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
