# Generated by Django 5.1.4 on 2026-08-05 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_impersonationsession_user_pf_number_and_more'),
        ('retail', '0003_saleitem_returned_quantity_salereturn_salereturnitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('opening_float', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('counted_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('over_short', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drawer_sessions', to='iam.organization')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='drawer_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='retail.drawersession'),
        ),
        migrations.AddIndex(
            model_name='drawersession',
            index=models.Index(fields=['organization', 'status'], name='retail_draw_organiz_c9526b_idx'),
        ),
        migrations.AddConstraint(
            model_name='drawersession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('organization', 'cashier'), name='one_open_drawer_per_cashier'),
        ),
    ]
