# Generated by Django 5.1.4 on 2026-08-06 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pricelist_product_ddd_product_is_essential_and_more'),
        ('iam', '0017_user_tin_payroll_email_reports_to'),
        ('retail', '0004_drawersession_sale_drawer_session_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('VACCINATION', 'Vaccination / Immunization'), ('SCREENING', 'Point-of-Care Testing (BP, Glucose, Malaria)'), ('CONSULTATION', 'Pharmacist Consultation'), ('PROCEDURE', 'Minor Clinical Procedure')], default='SCREENING', max_length=30)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='POSPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('promo_type', models.CharField(choices=[('PERCENT', 'Percentage Discount (%)'), ('FLAT', 'Flat Amount Off (RWF)'), ('BOGO', 'Buy One Get One')], default='PERCENT', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('min_spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_phone', models.CharField(blank=True, default='', max_length=20)),
                ('clinical_notes', models.TextField(blank=True, default='')),
                ('fee_charged', models.DecimalField(decimal_places=2, max_digits=14)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_encounters', to='iam.organization')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encounters', to='retail.clinicalservice')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlledSubstanceRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Receipt from Supplier/Depot'), ('DISPENSING', 'Dispensing to Patient'), ('DISPOSAL', 'Witnessed Disposal')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('running_balance', models.PositiveIntegerField()),
                ('patient_name', models.CharField(blank=True, default='', max_length=150)),
                ('prescriber_name', models.CharField(blank=True, default='', max_length=150)),
                ('witness_name', models.CharField(blank=True, default='', max_length=150)),
                ('rx_reference', models.CharField(blank=True, default='', max_length=100)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controlled_drug_logs', to='iam.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(max_length=50, unique=True)),
                ('patient_name', models.CharField(max_length=150)),
                ('patient_id_number', models.CharField(blank=True, default='', max_length=50)),
                ('patient_phone', models.CharField(blank=True, default='', max_length=20)),
                ('prescriber_name', models.CharField(max_length=150)),
                ('prescriber_license', models.CharField(blank=True, default='', max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('refills_allowed', models.PositiveIntegerField(default=1)),
                ('refills_used', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULFILLED', 'Fulfilled'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='iam.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
