# Generated by Django 5.1.4 on 2026-08-07 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0005_clinicalservice_pospromotion_clinicalservicerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensing',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensings', to='retail.prescription'),
        ),
    ]
