# Generated by Django 5.1.4 on 2026-08-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pricelist_product_ddd_product_is_essential_and_more'),
        ('retail', '0006_dispensing_prescription_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalservicerecord',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicalservicerecord',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_services', to='retail.sale'),
        ),
        migrations.AddField(
            model_name='pospromotion',
            name='max_redemptions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pospromotion',
            name='times_redeemed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='sale',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='retail.pospromotion'),
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_prescribed', models.PositiveIntegerField()),
                ('quantity_dispensed', models.PositiveIntegerField(default=0)),
                ('dosage_instructions', models.CharField(blank=True, default='', max_length=255)),
                ('substitution_allowed', models.BooleanField(default=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='retail.prescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('prescription', 'product'), name='uniq_prescription_item_product')],
            },
        ),
    ]
