# Generated by Django 5.1.4 on 2026-08-07 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0017_user_tin_payroll_email_reports_to'),
        ('retail', '0007_retail_model_completeness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_reference',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('client_reference__gt', '')), fields=('organization', 'client_reference'), name='uniq_sale_client_reference_per_org'),
        ),
    ]
