# Generated by Django 5.1.4 on 2026-08-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0008_offline_sale_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile money'), ('CARD', 'Card'), ('INSURANCE', 'Insurance (claimed)')], max_length=20),
        ),
    ]
