# Generated by Django 5.1.4 on 2026-08-07 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0019_seed_approval_limits'),
        ('retail', '0009_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='pospromotion',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Whose promotion this is. Empty means group-wide (set by HQ).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='iam.organization'),
        ),
        migrations.AlterField(
            model_name='pospromotion',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='pospromotion',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization', 'code'), name='uniq_promo_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='pospromotion',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('code',), name='uniq_group_wide_promo_code'),
        ),
    ]
