# Generated by Django 5.1.4 on 2026-08-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0010_tenant_scoped_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
