# Generated by Django 5.1.4 on 2026-08-09 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_seed_base_units'),
        ('retail', '0011_record_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='quantity_base',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.productunit'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='returned_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_item_quantity_is_positive'),
        ),
    ]
