# Generated by Django 5.1.4 on 2026-08-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0013_backfill_sale_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebatchallocation',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
    ]
