# Generated by Django 5.1.4 on 2026-08-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0014_alter_salebatchallocation_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlledsubstanceregister',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
        migrations.AlterField(
            model_name='controlledsubstanceregister',
            name='running_balance',
            field=models.DecimalField(decimal_places=3, max_digits=16),
        ),
    ]
