# Generated by Django 5.1.4 on 2026-08-04 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("iam", "0005_license"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE_ORDER", "Purchase order"),
                            ("PACKING_SLIP", "Packing slip"),
                            ("DELIVERY_NOTE", "Delivery note"),
                            ("GRN", "Goods received note"),
                            ("TAX_INVOICE", "Tax invoice"),
                            ("CREDIT_NOTE", "Credit note"),
                            ("RECEIPT", "Receipt"),
                        ],
                        max_length=30,
                    ),
                ),
                ("doc_number", models.CharField(max_length=40, unique=True)),
                ("reference_type", models.CharField(blank=True, default="", max_length=50)),
                ("reference_id", models.CharField(blank=True, default="", max_length=64)),
                ("file", models.FileField(upload_to="documents/%Y/%m/")),
                ("content_hash", models.CharField(max_length=64)),
                ("qr_token", models.CharField(max_length=32, unique=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="iam.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["reference_type", "reference_id"],
                        name="documents_d_referen_10afcf_idx",
                    ),
                    models.Index(
                        fields=["organization", "doc_type"], name="documents_d_organiz_982a56_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE_ORDER", "Purchase order"),
                            ("PACKING_SLIP", "Packing slip"),
                            ("DELIVERY_NOTE", "Delivery note"),
                            ("GRN", "Goods received note"),
                            ("TAX_INVOICE", "Tax invoice"),
                            ("CREDIT_NOTE", "Credit note"),
                            ("RECEIPT", "Receipt"),
                        ],
                        max_length=30,
                    ),
                ),
                ("year", models.IntegerField()),
                ("next_number", models.BigIntegerField(default=1)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="iam.organization"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "doc_type", "year"), name="uniq_doc_sequence"
                    )
                ],
            },
        ),
    ]
