# Generated by Django 5.1.4 on 2026-08-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE_ORDER", "Purchase order"),
                    ("PACKING_SLIP", "Packing slip"),
                    ("DELIVERY_NOTE", "Delivery note"),
                    ("GRN", "Goods received note"),
                    ("TAX_INVOICE", "Tax invoice"),
                    ("CREDIT_NOTE", "Credit note"),
                    ("RECEIPT", "Receipt"),
                    ("PAYSLIP", "Payslip"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="documentsequence",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE_ORDER", "Purchase order"),
                    ("PACKING_SLIP", "Packing slip"),
                    ("DELIVERY_NOTE", "Delivery note"),
                    ("GRN", "Goods received note"),
                    ("TAX_INVOICE", "Tax invoice"),
                    ("CREDIT_NOTE", "Credit note"),
                    ("RECEIPT", "Receipt"),
                    ("PAYSLIP", "Payslip"),
                ],
                max_length=30,
            ),
        ),
    ]
