# Generated by Django 5.1.4 on 2026-08-06 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_doc_type_and_more'),
        ('iam', '0017_user_tin_payroll_email_reports_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('organization', 'doc_number'), name='uniq_document_number_per_org'),
        ),
    ]
