# Generated by Django 5.1.4 on 2026-08-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_doc_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('PURCHASE_ORDER', 'Purchase order'), ('PACKING_SLIP', 'Packing slip'), ('DELIVERY_NOTE', 'Delivery note'), ('GRN', 'Goods received note'), ('TAX_INVOICE', 'Tax invoice'), ('CREDIT_NOTE', 'Credit note'), ('RECEIPT', 'Receipt'), ('PAYSLIP', 'Payslip'), ('DEBIT_NOTE', 'Debit note'), ('STATEMENT', 'Statement of account'), ('REMITTANCE_ADVICE', 'Remittance advice'), ('PAYMENT_VOUCHER', 'Payment voucher'), ('JOURNAL_VOUCHER', 'Journal voucher'), ('FINANCIAL_STATEMENT', 'Financial statements'), ('VAT_RETURN', 'VAT return')], max_length=30),
        ),
        migrations.AlterField(
            model_name='documentsequence',
            name='doc_type',
            field=models.CharField(choices=[('PURCHASE_ORDER', 'Purchase order'), ('PACKING_SLIP', 'Packing slip'), ('DELIVERY_NOTE', 'Delivery note'), ('GRN', 'Goods received note'), ('TAX_INVOICE', 'Tax invoice'), ('CREDIT_NOTE', 'Credit note'), ('RECEIPT', 'Receipt'), ('PAYSLIP', 'Payslip'), ('DEBIT_NOTE', 'Debit note'), ('STATEMENT', 'Statement of account'), ('REMITTANCE_ADVICE', 'Remittance advice'), ('PAYMENT_VOUCHER', 'Payment voucher'), ('JOURNAL_VOUCHER', 'Journal voucher'), ('FINANCIAL_STATEMENT', 'Financial statements'), ('VAT_RETURN', 'VAT return')], max_length=30),
        ),
    ]
