# Generated by Django 5.1.4 on 2026-08-07 19:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_pricelist_product_ddd_product_is_essential_and_more'),
        ('iam', '0017_user_tin_payroll_email_reports_to'),
        ('retail', '0009_alter_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(blank=True, default='', max_length=40, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('PART_PAID', 'Partially paid'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=12)),
                ('service_date', models.DateField()),
                ('patient_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('rejection_reason', models.CharField(blank=True, choices=[('NOT_ELIGIBLE', 'Member not eligible on the date of service'), ('NOT_COVERED', 'Product not on the scheme formulary'), ('NO_PRIOR_AUTH', 'Prior authorisation missing'), ('LATE_SUBMISSION', 'Submitted outside the claim window'), ('DUPLICATE', 'Duplicate of a claim already submitted'), ('PRICE_EXCEEDED', "Above the scheme's price ceiling"), ('QUANTITY_EXCEEDED', "Above the scheme's quantity limit"), ('OTHER', 'Other (see notes)')], default='', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('prior_auth_reference', models.CharField(blank=True, default='', max_length=60)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('adjudicated_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claims', to='iam.organization')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_claims', to='retail.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('patient_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('insurer_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('copay_pct_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='insurance.claim')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='retail.saleitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('CBHI', 'CBHI / Mutuelle de Santé'), ('RSSB_MEDICAL', 'RSSB medical (RAMA)'), ('MILITARY', 'Military medical insurance (MMI)'), ('PRIVATE', 'Private insurer'), ('EMPLOYER', 'Employer scheme')], default='PRIVATE', max_length=20)),
                ('settlement', models.CharField(choices=[('FEE_FOR_SERVICE', 'Fee for service (claim per dispense)'), ('CAPITATION', 'Capitation (funded upfront)')], default='FEE_FOR_SERVICE', max_length=20)),
                ('default_copay_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('claim_window_days', models.PositiveIntegerField(default=30)),
                ('contact_person', models.CharField(blank=True, default='', max_length=150)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_schemes', to='iam.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance.insurancescheme'),
        ),
        migrations.CreateModel(
            name='MemberPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(max_length=60)),
                ('group_number', models.CharField(blank=True, default='', max_length=60)),
                ('full_name', models.CharField(max_length=150)),
                ('national_id', models.CharField(blank=True, default='', max_length=30)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('relationship', models.CharField(choices=[('PRINCIPAL', 'Principal member'), ('SPOUSE', 'Spouse'), ('CHILD', 'Child'), ('DEPENDANT', 'Other dependant')], default='PRINCIPAL', max_length=15)),
                ('ubudehe_category', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('copay_pct_override', models.DecimalField(blank=True, decimal_places=2, help_text="Member's own co-payment share. Overrides the scheme rate; 0 means fully covered.", max_digits=5, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=12)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurance.insurancescheme')),
            ],
            options={
                'ordering': ['priority', 'full_name'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='insurance.memberpolicy'),
        ),
        migrations.CreateModel(
            name='RemittanceAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=10)),
                ('advice_date', models.DateField()),
                ('total_advised', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='iam.organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittances', to='insurance.insurancescheme')),
            ],
            options={
                'ordering': ['-advice_date'],
            },
        ),
        migrations.CreateModel(
            name='RemittanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('denial_reason', models.CharField(blank=True, default='', max_length=255)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remittance_lines', to='insurance.claim')),
                ('remittance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='insurance.remittanceadvice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SchemeFormulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_covered', models.BooleanField(default=True)),
                ('copay_pct_override', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('max_quantity_per_claim', models.PositiveIntegerField(blank=True, null=True)),
                ('requires_prior_auth', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_coverage', to='catalog.product')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulary', to='insurance.insurancescheme')),
            ],
            options={
                'verbose_name_plural': 'scheme formulary',
                'ordering': ['product__generic_name'],
            },
        ),
        migrations.AddIndex(
            model_name='insurancescheme',
            index=models.Index(fields=['organization', 'is_active'], name='insurance_i_organiz_99309e_idx'),
        ),
        migrations.AddConstraint(
            model_name='insurancescheme',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_scheme_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='memberpolicy',
            index=models.Index(fields=['member_number'], name='insurance_m_member__c0a4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='memberpolicy',
            index=models.Index(fields=['national_id'], name='insurance_m_nationa_03525c_idx'),
        ),
        migrations.AddConstraint(
            model_name='memberpolicy',
            constraint=models.UniqueConstraint(fields=('scheme', 'member_number'), name='uniq_member_per_scheme'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['organization', 'status'], name='insurance_c_organiz_fab010_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['scheme', 'status'], name='insurance_c_scheme__221eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['service_date'], name='insurance_c_service_ae8d3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='remittanceadvice',
            constraint=models.UniqueConstraint(fields=('organization', 'scheme', 'reference'), name='uniq_remittance_ref'),
        ),
        migrations.AddConstraint(
            model_name='remittanceline',
            constraint=models.UniqueConstraint(fields=('remittance', 'claim'), name='uniq_remittance_claim'),
        ),
        migrations.AddConstraint(
            model_name='schemeformulary',
            constraint=models.UniqueConstraint(fields=('scheme', 'product'), name='uniq_formulary_scheme_product'),
        ),
    ]
